### ISSUE TITLE
In 4.2.4, 1f Fit .csv Export Successful but Data .csv Export Unsuccessful 

### ISSUE THREAD

**Issue by joticknor** [dfujim/bfit#79] opened 2020-11-19 07:01 UTC
When attempting to export run 2018:40927, the 2018_40927_fit.csv works but not the 2018_40927.csv data file. But it does appear to work for SLR (for example 2018_40926.csv) regardless of whether it is binned or not.

See the screengrab of the traceback for attempting to export the data file. 
![bfit-x](https://user-images.githubusercontent.com/57420764/99632308-da39a480-29f1-11eb-88fd-a2df9be3d077.png)

**Comment by dfujim** [comment] 2020-11-19 07:39
The issue is related to a decision error in bdata. Resolved in a6ba5e12f25ebe76b07df881913be73682f602b9

**Closed by dfujim** 2020-11-19 07:39 UTC
